# Generated by Django 3.0.5 on 2020-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200416_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepad',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
