# Generated by Django 3.0.5 on 2020-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
